export type LearningGuide = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  image: string;
  path: "artist" | "engineer";
};

export const learningGuides = [
  { slug: "build-levels-in-blender-for-godot", title: "How to Make a Playable Godot Level in Blender", shortTitle: "Make a Playable Level", description: "Turn Blender geometry into a correctly scaled, collidable level and prove the complete GLB-to-Godot workflow.", image: "/docs/thumbs/sub-scene.png", path: "artist" },
  { slug: "create-player-in-blender-for-godot", title: "How to Add a Player in Blender for Godot", shortTitle: "Add a Player in Blender", description: "Create a correctly scaled player and choose first-person, third-person, camera, and hold-zone settings.", image: "/docs/thumbs/characters.png", path: "artist" },
  { slug: "create-triggers-in-blender-for-godot", title: "How to Create Triggers in Blender for Godot", shortTitle: "Create Blender Triggers", description: "Draw trigger volumes where the action belongs, filter participants, and dispatch named gameplay events.", image: "/docs/thumbs/triggers.png", path: "artist" },
  { slug: "make-doors-switches-in-blender", title: "How to Make Doors and Switches Work from Blender", shortTitle: "Make Doors and Switches", description: "Combine Blender animations, triggers, speakers, and Scene Event commands into a satisfying interaction.", image: "/docs/thumbs/animation.png", path: "artist" },
  { slug: "physics-objects-in-blender-for-godot", title: "How to Add Physics Objects in Blender for Godot", shortTitle: "Add Physics in Blender", description: "Author collision, mass, friction, bounciness, and fast-moving-body protection before export.", image: "/docs/thumbs/physics.png", path: "artist" },
  { slug: "holdable-items-godot", title: "How to Create Inventory Pickups and Holdable Items in Blender", shortTitle: "Pickups and Holdable Items", description: "Choose between stackable inventory data and a physical prop the player carries through the world.", image: "/docs/thumbs/inventory.png", path: "artist" },
  { slug: "play-3d-audio-godot", title: "How to Add 3D Audio and Background Music in Blender", shortTitle: "Add Audio in Blender", description: "Turn scene objects into positioned speakers and give the whole level music without writing playback scripts.", image: "/docs/thumbs/audio.png", path: "artist" },
  { slug: "animation-frame-events-godot", title: "How to Trigger Gameplay from Blender Animation Frames", shortTitle: "Trigger Animation Events", description: "Place meaningful events on exact Blender frames for footsteps, impacts, sounds, cameras, and scene changes.", image: "/docs/thumbs/animation.png", path: "artist" },
  { slug: "switch-cameras-godot", title: "How to Switch Cameras and Create Cutscenes from Blender", shortTitle: "Create Camera Cuts", description: "Author cameras in the scene, pause player control, run the shot, and return to the player safely.", image: "/docs/thumbs/cameras.png", path: "artist" },
  { slug: "change-scenes-load-levels-godot", title: "How to Load Levels and Interiors from Blender", shortTitle: "Load Levels and Interiors", description: "Choose full level changes or streamed sub-scenes and author the transition where the doorway lives.", image: "/docs/thumbs/sub-scene.png", path: "artist" },
  { slug: "world-settings-in-blender-for-godot", title: "How to Set Up Your Godot Game World in Blender", shortTitle: "Set Up the Game World", description: "Choose sky color, gravity, music, and commands that run as your authored level loads and unloads.", image: "/docs/thumbs/scene-settings.png", path: "artist" },
  { slug: "blender-to-godot-gameplay-import", title: "How FPE Turns Blender Properties into Godot Gameplay", shortTitle: "Blender Properties to Gameplay", description: "Understand the standard glTF contract that carries an artist's gameplay decisions into inspectable Godot nodes.", image: "/docs/thumbs/pipeline.png", path: "engineer" },
  { slug: "instant-game-mechanics", title: "What Are Instant Game Mechanics?", shortTitle: "Instant Game Mechanics", description: "See how artists can own repeatable gameplay setup while engineers keep control of the unique systems.", image: "/docs/thumbs/characters.png", path: "engineer" },
  { slug: "godot-inventory-system", title: "How to Build and Extend an Inventory System in Godot", shortTitle: "Extend an Inventory System", description: "Model item data, stacking, partial transfers, saves, and UI beyond the Blender-authored pickup.", image: "/docs/thumbs/inventory.png", path: "engineer" },
  { slug: "godot-trigger-system", title: "How to Extend FPE Triggers in Godot", shortTitle: "Extend FPE Triggers", description: "Understand the Area3D pattern beneath authored triggers and connect custom systems without brittle node paths.", image: "/docs/thumbs/triggers.png", path: "engineer" },
  { slug: "interactive-objects-godot", title: "How to Add Custom Interactions to FPE Objects in Godot", shortTitle: "Add Custom Interactions", description: "Add player targeting and unique behaviors while preserving the repeated setup imported from Blender.", image: "/docs/thumbs/physics.png", path: "engineer" },
  { slug: "save-restore-fpe-game-state-godot", title: "How to Save and Restore FPE Game State in Godot", shortTitle: "Save and Restore Game State", description: "Persist player and character inventories, collected objects, named events, and animation-driven world state across FPE level loads.", image: "/docs/thumbs/pipeline.png", path: "engineer" },
  { slug: "dialogue-triggers-godot", title: "How to Connect Blender Triggers to Dialogue in Godot", shortTitle: "Connect Triggers to Dialogue", description: "Start Godot-authored conversation resources from Blender-authored events and keep UI separate from progression.", image: "/docs/thumbs/conversations.png", path: "engineer" },
  { slug: "blender-godot-import-troubleshooting", title: "How to Fix Blender-to-Godot Import Problems", shortTitle: "Fix Blender-to-Godot Imports", description: "Trace missing mechanics through Blender settings, GLB export, Godot reimport, and FPE runtime behavior.", image: "/docs/thumbs/troubleshooting.png", path: "engineer" },
] satisfies LearningGuide[];
